// Whenever i think that i will get some error.So, i make that 
// code inside the try, inside the try we write the code which i 
// feel that that code may be wrong and its after catch also to 
// catch the wrong code which i made wrong.

// try{
//     console.log("Hello World");

// }
// catch(err){
//console.log(err);
//     // here we write the code which will run when the code inside the try will get wrong.
// }



let a=5;
let b=6;
console.log("a=",a);
console.log("b",b);
console.log("a+b=",a+b);
console.log("a+b=",a+b);
try{
console.log("a+b=",a+c);//Here i have made an error
}catch(err){
console.log(err);

}
console.log("a+b=",a+b);
console.log("a+b=",a+b);
console.log("a+b=",a+b);
console.log("a+b=",a+b);

// What happens in JavaScript that whenever any error comes in the code 
// it stops there to go ahead for the execution  SourceBuffer, we use try ,catch  so that we write code in try 
// and if there is some wrong thing catch ,catches it and showWinner.